import https from 'https';

/**
 * Error thrown when transcript fetch fails but page data was retrieved.
 * Carries isLive and metadata so callers can redirect to live chat.
 */
export class TranscriptFetchError extends Error {
  isLive: boolean;
  metadata: VideoMetadata;
  constructor(message: string, isLive: boolean, metadata: VideoMetadata) {
    super(message);
    this.name = 'TranscriptFetchError';
    this.isLive = isLive;
    this.metadata = metadata;
  }
}

export interface TranscriptLine {
  text: string;
  start: number;
  dur: number;
}

interface CaptionTrack {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

export interface AdChapter {
  title: string;
  startMs: number;
  endMs: number;
}

export interface VideoMetadata {
  title: string;
  author: string;
  subscriberCount: string;
  viewCount: string;
  commentCount: string;
  publishDate: string;
  duration: string;
}

export interface Chapter {
  title: string;
  startMs: number;
  isAd: boolean;
}

export interface Comment {
  author: string;
  authorChannelId: string;
  text: string;
  likes: string;
  replyCount: number;
  publishedTime: string;
  isPinned: boolean;
  isHearted: boolean;
  commentId: string;
  isReply: boolean;
  parentId?: string;
}

interface PageData {
  visitorData: string;
  clientVersion: string;
  availableLanguages: CaptionTrack[];
  chapters: Chapter[];
  adChapters: AdChapter[];
  metadata: VideoMetadata;
  isLive: boolean;
  commentCount?: number;  // Optional - requires separate API call
}

const REQUEST_TIMEOUT = 30000; // 30 seconds

/**
 * Formats a number as compact string: 1234 → "1.2k", 1234567 → "1.2M"
 */
export function formatCount(n: number): string {
  if (Number.isNaN(n) || n <= 0) return '';
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(1) + 'M';
  if (n >= 1_000) return (n / 1_000).toFixed(1) + 'k';
  return n.toString();
}

// TODO: These versions may need periodic updates if YouTube starts rejecting old clients
// The ANDROID client is used to bypass YouTube's poToken A/B test enforcement
const ANDROID_CLIENT_VERSION = '19.29.37';
const ANDROID_USER_AGENT = `com.google.android.youtube/${ANDROID_CLIENT_VERSION} (Linux; U; Android 11) gzip`;
const WEB_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const DEFAULT_CLIENT_VERSION = '2.20251201.01.00'; // Fallback if not extracted from page

/**
 * Encodes a number as a protobuf varint
 * Handles lengths > 127 correctly (multi-byte encoding)
 */
function encodeVarint(value: number): number[] {
  const bytes: number[] = [];
  while (value > 0x7f) {
    bytes.push((value & 0x7f) | 0x80);
    value >>>= 7;
  }
  bytes.push(value);
  return bytes;
}

/**
 * Builds the protobuf-encoded params for the transcript API
 * @param isAsr - true for auto-generated captions (ASR), false for uploaded/manual captions
 */
function buildParams(videoId: string, lang: string = 'en', isAsr: boolean = true): string {
  // Inner protobuf: language params
  // For ASR captions: includes "asr" field
  // For uploaded captions: omits "asr" field
  const innerParts: number[] = isAsr
    ? [
        0x0a, 0x03, ...Buffer.from('asr'),           // Field 1, "asr" (only for auto-generated)
        0x12, ...encodeVarint(lang.length), ...Buffer.from(lang),  // Field 2, language code
        0x1a, 0x00                                    // Field 3, empty
      ]
    : [
        0x12, ...encodeVarint(lang.length), ...Buffer.from(lang),  // Field 2, language code
        0x1a, 0x00                                    // Field 3, empty
      ];
  const innerBuf = Buffer.from(innerParts);
  const innerB64 = innerBuf.toString('base64');
  const innerEncoded = encodeURIComponent(innerB64);

  // Outer protobuf
  const panelName = 'engagement-panel-searchable-transcript-search-panel';
  const outerParts: number[] = [
    0x0a, ...encodeVarint(videoId.length), ...Buffer.from(videoId),      // Field 1, video ID
    0x12, ...encodeVarint(innerEncoded.length), ...Buffer.from(innerEncoded), // Field 2, language params
    0x18, 0x01,                                          // Field 3, value 1
    0x2a, ...encodeVarint(panelName.length), ...Buffer.from(panelName),  // Field 5, panel name
    0x30, 0x01,                                          // Field 6, value 1
    0x38, 0x01,                                          // Field 7, value 1
    0x40, 0x01                                           // Field 8, value 1
  ];

  return Buffer.from(outerParts).toString('base64');
}

/**
 * Builds the protobuf-encoded params for the comments API
 * Structure: GetCommentsSectionParams from YouTube.js proto definitions
 */
function buildCommentsParams(videoId: string, sortBy: 0 | 1 = 0): string {
  // Helper to encode a string field
  const encodeString = (fieldNum: number, str: string): number[] => {
    const tag = (fieldNum << 3) | 2; // wire type 2 = length-delimited
    return [tag, ...encodeVarint(str.length), ...Buffer.from(str)];
  };

  // Helper to encode a varint field
  const encodeVarField = (fieldNum: number, value: number): number[] => {
    const tag = (fieldNum << 3) | 0; // wire type 0 = varint
    return [tag, ...encodeVarint(value)];
  };

  // Helper to encode a submessage
  const encodeSubmessage = (fieldNum: number, content: number[]): number[] => {
    const tag = (fieldNum << 3) | 2;
    return [tag, ...encodeVarint(content.length), ...content];
  };

  // Build Options (field 4 of Params)
  // video_id=4, sort_by=6, type=15
  const options: number[] = [
    ...encodeString(4, videoId),
    ...encodeVarField(6, sortBy),
    ...encodeVarField(15, 2)  // type = 2
  ];

  // Build Params (field 6)
  // opts=4, target=8
  const params: number[] = [
    ...encodeSubmessage(4, options),
    ...encodeString(8, 'comments-section')
  ];

  // Build Context (field 2)
  const ctx: number[] = [
    ...encodeString(2, videoId)
  ];

  // Build full GetCommentsSectionParams
  // ctx=2, unk_param=3, params=6
  const full: number[] = [
    ...encodeSubmessage(2, ctx),
    ...encodeVarField(3, 6),  // unk_param = 6
    ...encodeSubmessage(6, params)
  ];

  return Buffer.from(full).toString('base64');
}

/**
 * Makes an HTTPS request and returns the response body
 * Includes timeout and HTTP status code validation
 */
function httpsRequest(options: https.RequestOptions, data?: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const req = https.request({ ...options, timeout: REQUEST_TIMEOUT }, (res) => {
      // Validate HTTP status code
      if (res.statusCode && (res.statusCode < 200 || res.statusCode >= 300)) {
        reject(new Error(`HTTP ${res.statusCode}: ${res.statusMessage || 'Unknown error'}`));
        return;
      }

      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => resolve(body));
    });

    req.on('error', (err) => {
      reject(new Error(`Network error: ${err.message}`));
    });

    req.on('timeout', () => {
      req.destroy();
      reject(new Error(`Request timeout after ${REQUEST_TIMEOUT}ms`));
    });

    if (data) req.write(data);
    req.end();
  });
}

/**
 * Fetches the YouTube video page and extracts visitor data and client version
 */
async function getPageData(videoId: string): Promise<PageData> {
  let html: string;

  try {
    html = await httpsRequest({
      hostname: 'www.youtube.com',
      path: `/watch?v=${videoId}`,
      method: 'GET',
      headers: {
        'User-Agent': WEB_USER_AGENT,
        'Accept-Language': 'en-US,en;q=0.9'
      }
    });
  } catch (err) {
    throw new Error(`Failed to fetch video page: ${(err as Error).message}`);
  }

  // Check for video availability issues
  if (html.includes('"status":"LOGIN_REQUIRED"') ||
      html.includes('"reason":"Sign in to confirm your age') ||
      html.includes('ageGate') ||
      html.includes('"AGE_VERIFICATION_REQUIRED"')) {
    throw new Error('This video is age-restricted and requires sign-in to view. Transcripts cannot be retrieved for age-restricted content.');
  }

  if (html.includes('"status":"UNPLAYABLE"') || html.includes('"status":"ERROR"')) {
    // Extract reason if available
    const reasonMatch = html.match(/"reason":"([^"]+)"/);
    const reason = reasonMatch?.[1] || 'Video is unavailable';
    throw new Error(`Video unavailable: ${reason}`);
  }

  if (html.includes('"isPrivate":true')) {
    throw new Error('This video is private and cannot be accessed.');
  }

  if (html.includes('"status":"LIVE_STREAM_OFFLINE"')) {
    throw new Error('This is a live stream that is currently offline. No transcript available.');
  }

  // Extract visitor data
  const visitorMatch = html.match(/"visitorData":"([^"]+)"/);
  const visitorData = visitorMatch?.[1] || '';

  if (!visitorData) {
    console.error(`[youtube-fetcher] Warning: Could not extract visitorData for video ${videoId}. Request may fail.`);
  }

  // Extract client version (format: "2.YYYYMMDD.XX.XX")
  const versionMatch = html.match(/"clientVersion":"([\d.]+)"/);
  const clientVersion = versionMatch?.[1] || DEFAULT_CLIENT_VERSION;

  // Extract available caption tracks
  const availableLanguages: CaptionTrack[] = [];
  const captionsMatch = html.match(/"captions":\{"playerCaptionsTracklistRenderer":\{"captionTracks":(\[[^\]]+\])/);
  if (captionsMatch) {
    try {
      const tracks = JSON.parse(captionsMatch[1]);
      for (const track of tracks) {
        if (track.languageCode) {
          availableLanguages.push({
            languageCode: track.languageCode,
            name: track.name?.simpleText || track.name?.runs?.[0]?.text || track.languageCode,
            isAutoGenerated: track.kind === 'asr'
          });
        }
      }
    } catch (e) {
      console.error(`[youtube-fetcher] Warning: Could not parse caption tracks for video ${videoId}`);
    }
  }

  // Extract chapters and identify ad chapters
  const adChapters: AdChapter[] = [];
  const adMarkers = [
    '(werbung)', '(ad)', '(ads)', '(sponsor)', '(sponsored)',
    '(promo)', '(promotion)', '(anzeige)', '(reklame)',
    '[werbung]', '[ad]', '[ads]', '[sponsor]', '[sponsored]',
    '[promo]', '[promotion]', '[anzeige]', '[reklame]'
  ];

  // Extract chapters from chapterRenderer elements using individual field matches
  // Each chapterRenderer has a title and timeRangeStartMillis - extract all instances
  const chapters: Chapter[] = [];
  let searchPos = 0;
  while (true) {
    const chapterIdx = html.indexOf('"chapterRenderer"', searchPos);
    if (chapterIdx === -1) break;

    // Find the next chapterRenderer boundary (or end of string) for scoping
    const nextChapterIdx = html.indexOf('"chapterRenderer"', chapterIdx + 1);
    const chapterBlock = html.slice(chapterIdx, nextChapterIdx !== -1 ? nextChapterIdx : chapterIdx + 2000);

    // Extract title - try simpleText first, then runs[0].text
    const titleSimple = chapterBlock.match(/"title":\s*\{\s*"simpleText":\s*"([^"]+)"/);
    const titleRuns = chapterBlock.match(/"title":\s*\{\s*"runs":\s*\[\s*\{\s*"text":\s*"([^"]+)"/);
    const title = titleSimple?.[1] || titleRuns?.[1] || '';

    // Extract time
    const timeMatch = chapterBlock.match(/"timeRangeStartMillis":\s*"?(\d+)"?/);
    const startMs = timeMatch ? parseInt(timeMatch[1], 10) : -1;

    if (title && startMs >= 0) {
      chapters.push({
        title,
        startMs,
        isAd: adMarkers.some(marker => title.toLowerCase().includes(marker))
      });
    }

    searchPos = chapterIdx + 1;
  }

  // Convert ad chapters to AdChapter format with end times
  for (let i = 0; i < chapters.length; i++) {
    if (chapters[i].isAd) {
      const nextChapter = chapters[i + 1];
      // End time is start of next chapter, or +5 minutes if last chapter
      const endMs = nextChapter ? nextChapter.startMs : chapters[i].startMs + 300000;
      adChapters.push({
        title: chapters[i].title,
        startMs: chapters[i].startMs,
        endMs: endMs
      });
    }
  }

  // Extract video metadata (target videoDetails block, use .*? for nested objects)
  const titleMatch = html.match(/"videoDetails":\{.*?"title":"([^"]+)"/);
  const authorMatch = html.match(/"videoDetails":\{.*?"author":"([^"]+)"/);
  const subsMatch = html.match(/"subscriberCountText":\{"accessibility":\{"accessibilityData":\{"label":"([^"]+)"/);
  const viewsMatch = html.match(/"viewCount":"(\d+)"/);
  const dateMatch = html.match(/"publishDate":"([^"]+)"/);
  const lengthMatch = html.match(/"videoDetails":\{.*?"lengthSeconds":"(\d+)"/);
  
  // Extract comment count (may be in different locations in the HTML)
  const commentCountMatch = html.match(/"commentCount":"?(\d+)"?/) || 
                            html.match(/"commentCountText":\{"runs":\[\{"text":"([\d,]+)"/);

  // Shorten subscriber count: "649 thousand subscribers" → "649k"
  let subs = subsMatch?.[1] || '';
  subs = subs.replace(/ subscribers?/i, '').replace(/ thousand/i, 'k').replace(/ million/i, 'M').replace(/ billion/i, 'B');

  // Format view count and comment count
  const viewNum = parseInt(viewsMatch?.[1] || '', 10);
  const viewsFormatted = formatCount(viewNum);

  const commentNum = parseInt((commentCountMatch?.[1] || '').replace(/,/g, ''), 10);
  const commentsFormatted = formatCount(commentNum);

  // Shorten date: "2025-12-03T03:01:16-08:00" → "2025-12-03"
  const dateRaw = dateMatch?.[1] || '';
  const dateShort = dateRaw.split('T')[0];

  // Format duration: 212 → "3:32", 3661 → "1:01:01"
  const lengthSecs = parseInt(lengthMatch?.[1] || '0', 10);
  let durationFormatted = '';
  if (lengthSecs > 0) {
    const hrs = Math.floor(lengthSecs / 3600);
    const mins = Math.floor((lengthSecs % 3600) / 60);
    const secs = lengthSecs % 60;
    durationFormatted = hrs > 0
      ? `${hrs}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`
      : `${mins}:${secs.toString().padStart(2, '0')}`;
  }

  const metadata: VideoMetadata = {
    title: titleMatch?.[1] || '',
    author: authorMatch?.[1] || '',
    subscriberCount: subs,
    viewCount: viewsFormatted,
    commentCount: commentsFormatted,
    publishDate: dateShort,
    duration: durationFormatted
  };

  // Detect live streams
  const isLive = html.includes('"isLiveContent":true') || html.includes('"isLive":true');

  return { visitorData, clientVersion, availableLanguages, chapters, adChapters, metadata, isLive };
}

export interface SubtitleResult {
  lines: TranscriptLine[];
  requestedLang: string;
  actualLang: string;
  availableLanguages: CaptionTrack[];
  chapters: Chapter[];
  adChapters: AdChapter[];
  metadata: VideoMetadata;
  isLive: boolean;
}

/**
 * Returns available caption languages for a video without fetching the full transcript
 */
export async function getAvailableLanguages(videoID: string): Promise<CaptionTrack[]> {
  if (!videoID || typeof videoID !== 'string') {
    throw new Error('Invalid video ID: must be a non-empty string');
  }
  const { availableLanguages } = await getPageData(videoID);
  return availableLanguages;
}

/**
 * Fetches just the comment count for a video without fetching all comments
 * Makes a single API call to get the count from the comments header
 */
export async function getCommentCount(videoID: string): Promise<number> {
  if (!videoID || typeof videoID !== 'string') {
    throw new Error('Invalid video ID: must be a non-empty string');
  }

  const { visitorData, clientVersion } = await getPageData(videoID);
  const continuationToken = encodeURIComponent(buildCommentsParams(videoID, 0));

  const payload = JSON.stringify({
    context: {
      client: {
        hl: 'en',
        gl: 'US',
        clientName: 'WEB',
        clientVersion: clientVersion,
        visitorData: visitorData
      }
    },
    continuation: continuationToken
  });

  try {
    const response = await httpsRequest({
      hostname: 'www.youtube.com',
      path: '/youtubei/v1/next?prettyPrint=false',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(payload),
        'User-Agent': WEB_USER_AGENT,
        'Origin': 'https://www.youtube.com'
      }
    }, payload);

    const json = JSON.parse(response);
    const endpoints = json.onResponseReceivedEndpoints || [];

    for (const endpoint of endpoints) {
      const items = endpoint.reloadContinuationItemsCommand?.continuationItems ||
                    endpoint.appendContinuationItemsAction?.continuationItems || [];
      for (const item of items) {
        if (item.commentsHeaderRenderer) {
          const countText = item.commentsHeaderRenderer.countText?.runs?.[0]?.text || '';
          const countMatch = countText.match(/[\d,]+/);
          if (countMatch) {
            return parseInt(countMatch[0].replace(/,/g, ''), 10);
          }
        }
      }
    }
  } catch (err) {
    console.error('[youtube-fetcher] Error fetching comment count:', err);
  }

  return 0;
}

/**
 * Fetches transcript using the YouTube internal API
 * If the requested language is not available and enableFallback is true,
 * it will try English first, then fall back to the first available language.
 */
export async function getSubtitles(options: {
  videoID: string;
  lang?: string;
  enableFallback?: boolean;
}): Promise<SubtitleResult> {
  const { videoID, lang = 'en', enableFallback = true } = options;

  // Validate video ID format
  if (!videoID || typeof videoID !== 'string') {
    throw new Error('Invalid video ID: must be a non-empty string');
  }

  // Get page data (visitor data needed for API authentication)
  console.error(`[youtube-fetcher] Fetching page data for video: ${videoID}`);
  const { visitorData, availableLanguages, chapters, adChapters, metadata, isLive } = await getPageData(videoID);
  console.error(`[youtube-fetcher] Page data: title="${metadata.title}", visitorData=${visitorData ? 'present' : 'MISSING'}, availableLanguages=[${availableLanguages.map(l => l.languageCode).join(',')}]`);

  // Determine which language to use and whether it's ASR
  let targetLang = lang;
  let isAsr = true; // Default to ASR for backwards compatibility

  if (availableLanguages.length > 0) {
    const requestedTrack = availableLanguages.find(t => t.languageCode === lang);
    const hasRequestedLang = !!requestedTrack;

    if (!hasRequestedLang && enableFallback) {
      // Try English first
      const englishTrack = availableLanguages.find(t => t.languageCode === 'en');
      if (englishTrack) {
        targetLang = 'en';
        isAsr = englishTrack.isAutoGenerated;
        console.error(`[youtube-fetcher] Language '${lang}' not available, falling back to 'en' (isAsr=${isAsr})`);
      } else {
        // Use first available
        targetLang = availableLanguages[0].languageCode;
        isAsr = availableLanguages[0].isAutoGenerated;
        console.error(`[youtube-fetcher] Language '${lang}' not available, falling back to '${targetLang}' (isAsr=${isAsr})`);
      }
    } else if (!hasRequestedLang) {
      throw new Error(`Language '${lang}' not available. Available: ${availableLanguages.map(t => t.languageCode).join(', ')}`);
    } else {
      isAsr = requestedTrack!.isAutoGenerated;
    }
  }

  console.error(`[youtube-fetcher] Building params for lang=${targetLang}, isAsr=${isAsr}`);

  // Build params and try multiple clients until we get segments
  const params = buildParams(videoID, targetLang, isAsr);

  const androidPayload = JSON.stringify({
    context: {
      client: {
        hl: targetLang,
        gl: 'US',
        clientName: 'ANDROID',
        clientVersion: ANDROID_CLIENT_VERSION,
        androidSdkVersion: 30,
        visitorData: visitorData
      }
    },
    params: params
  });

  // Try TVHTML5 (TV app) which often has different API behavior
  const tvPayload = JSON.stringify({
    context: {
      client: {
        hl: targetLang,
        gl: 'US',
        clientName: 'TVHTML5',
        clientVersion: '7.20211222.00.00',
        visitorData: visitorData
      }
    },
    params: params
  });

  // Try iOS client
  const iosPayload = JSON.stringify({
    context: {
      client: {
        hl: targetLang,
        gl: 'US',
        clientName: 'IOS',
        clientVersion: '19.29.1',
        visitorData: visitorData
      }
    },
    params: params
  });

  const payloads = [
    { name: 'ANDROID', payload: androidPayload, userAgent: ANDROID_USER_AGENT },
    { name: 'IOS', payload: iosPayload, userAgent: 'com.google.ios.youtube/19.29.1 (iPhone16,2; U; CPU iOS 17_5_1 like Mac OS X;)' },
    { name: 'TVHTML5', payload: tvPayload, userAgent: 'Mozilla/5.0 (SMART-TV; LINUX; Tizen 6.0) AppleWebKit/537.36 (KHTML, like Gecko) 80.0.3987.149/6.0 TV Safari/537.36' }
  ];

  // Try each client until we get segments
  let response: string = '';
  let json: any = null;
  let segments: any[] = [];
  let lastError: Error | null = null;

  for (const { name, payload, userAgent } of payloads) {
    try {
      console.error(`[youtube-fetcher] Trying ${name} client...`);
      response = await httpsRequest({
        hostname: 'www.youtube.com',
        path: '/youtubei/v1/get_transcript?prettyPrint=false',
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(payload),
          'User-Agent': userAgent,
          'Origin': 'https://www.youtube.com'
        }
      }, payload);

      // Parse response
      try {
        json = JSON.parse(response);
      } catch (err) {
        console.error(`[youtube-fetcher] ${name} client: failed to parse response`);
        continue;
      }

      // Check for API-level errors
      if (json.error) {
        console.error(`[youtube-fetcher] ${name} client: API error: ${json.error.message || json.error.code}`);
        continue;
      }

      // Extract transcript segments - handle both WEB and ANDROID response formats
      const webSegments = json?.actions?.[0]?.updateEngagementPanelAction?.content
        ?.transcriptRenderer?.content?.transcriptSearchPanelRenderer?.body
        ?.transcriptSegmentListRenderer?.initialSegments;

      const androidSegments = json?.actions?.[0]?.elementsCommand?.transformEntityCommand
        ?.arguments?.transformTranscriptSegmentListArguments?.overwrite?.initialSegments;

      segments = webSegments || androidSegments || [];
      console.error(`[youtube-fetcher] ${name} client: found ${segments.length} segments`);

      if (segments.length > 0) {
        break; // Found segments, stop trying
      }
    } catch (err) {
      lastError = err as Error;
      console.error(`[youtube-fetcher] ${name} client error: ${(err as Error).message}`);
    }
  }

  if (!json) {
    throw new TranscriptFetchError(`Failed to fetch transcript API: ${lastError?.message || 'Unknown error'}`, isLive, metadata);
  }

  // If no segments found, check for continuation key in frameworkUpdates
  if (segments.length === 0) {
    console.error(`[youtube-fetcher] No segments in initial response, checking for continuation key...`);
    const fw = json?.frameworkUpdates;
    const mutations = fw?.entityBatchUpdate?.mutations || [];

    for (const mut of mutations) {
      const tsde = mut.payload?.transcriptSegmentsDataEntity;
      if (tsde?.key) {
        console.error(`[youtube-fetcher] Found continuation key: ${tsde.key}`);

        // Make a follow-up request with the continuation key
        const continuationPayload = JSON.stringify({
          context: {
            client: {
              hl: targetLang,
              gl: 'US',
              clientName: 'ANDROID',
              clientVersion: ANDROID_CLIENT_VERSION,
              androidSdkVersion: 30,
              visitorData: visitorData
            }
          },
          continuation: tsde.key
        });

        try {
          console.error(`[youtube-fetcher] Fetching segments with continuation key...`);
          const contResponse = await httpsRequest({
            hostname: 'www.youtube.com',
            path: '/youtubei/v1/get_transcript?prettyPrint=false',
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Content-Length': Buffer.byteLength(continuationPayload),
              'User-Agent': ANDROID_USER_AGENT,
              'Origin': 'https://www.youtube.com'
            }
          }, continuationPayload);

          const contJson = JSON.parse(contResponse);
          console.error(`[youtube-fetcher] Continuation response keys: ${JSON.stringify(Object.keys(contJson))}`);

          // Try to extract segments from continuation response
          const contWebSegments = contJson?.actions?.[0]?.updateEngagementPanelAction?.content
            ?.transcriptRenderer?.content?.transcriptSearchPanelRenderer?.body
            ?.transcriptSegmentListRenderer?.initialSegments;

          const contAndroidSegments = contJson?.actions?.[0]?.elementsCommand?.transformEntityCommand
            ?.arguments?.transformTranscriptSegmentListArguments?.overwrite?.initialSegments;

          // Also check frameworkUpdates in continuation response
          const contMutations = contJson?.frameworkUpdates?.entityBatchUpdate?.mutations || [];
          let mutationSegments: any[] = [];
          for (const contMut of contMutations) {
            const segData = contMut.payload?.transcriptSegmentRenderer;
            if (segData) {
              mutationSegments.push({ transcriptSegmentRenderer: segData });
            }
          }

          segments = contWebSegments || contAndroidSegments || mutationSegments || [];
          console.error(`[youtube-fetcher] Continuation found ${segments.length} segments`);

          if (segments.length > 0) {
            break;
          }
        } catch (err) {
          console.error(`[youtube-fetcher] Continuation request failed: ${(err as Error).message}`);
        }
      }
    }
  }

  if (segments.length === 0) {
    throw new TranscriptFetchError('No transcript available for this video. The video may not have captions enabled.', isLive, metadata);
  }

  // Convert to TranscriptLine format
  const lines = segments
    .filter((seg: any) => seg?.transcriptSegmentRenderer) // Skip section headers
    .map((seg: any) => {
      const renderer = seg.transcriptSegmentRenderer;

      // Handle both WEB format (snippet.runs) and ANDROID format (snippet.elementsAttributedString)
      const webText = renderer?.snippet?.runs?.map((r: any) => r.text || '').join('');
      const androidText = renderer?.snippet?.elementsAttributedString?.content;
      const text = webText || androidText || '';

      const startMs = parseInt(renderer?.startMs || '0', 10);
      const endMs = parseInt(renderer?.endMs || '0', 10);

      return {
        text: text,
        start: startMs / 1000,
        dur: (endMs - startMs) / 1000
      };
    })
    .filter((line: TranscriptLine) => line.text.length > 0);

  // commentCount is already extracted from the page HTML in getPageData
  // No need for a separate API call that re-fetches the entire page

  return {
    lines,
    requestedLang: lang,
    actualLang: targetLang,
    availableLanguages,
    chapters,
    adChapters,
    metadata,
    isLive
  };
}

export interface CommentsResult {
  comments: Comment[];
  totalCount: number;
  continuation?: string;
}

interface CommentPageResult {
  comments: Comment[];
  totalCount: number;
  continuation?: string;
  replyTokens: Map<string, string>; // commentId -> reply continuation token
}

/**
 * Fetches a single page of comments using a continuation token
 */
async function fetchCommentsPage(
  continuationToken: string,
  visitorData: string,
  clientVersion: string
): Promise<CommentPageResult> {
  const payload = JSON.stringify({
    context: {
      client: {
        hl: 'en',
        gl: 'US',
        clientName: 'WEB',
        clientVersion: clientVersion,
        visitorData: visitorData
      }
    },
    continuation: continuationToken
  });

  const response = await httpsRequest({
    hostname: 'www.youtube.com',
    path: '/youtubei/v1/next?prettyPrint=false',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Content-Length': Buffer.byteLength(payload),
      'User-Agent': WEB_USER_AGENT,
      'Origin': 'https://www.youtube.com'
    }
  }, payload);

  const json = JSON.parse(response);
  if (json.error) {
    throw new Error(`YouTube API error: ${json.error.message || 'Unknown error'}`);
  }

  const comments: Comment[] = [];
  let totalCount = 0;
  let nextContinuation: string | undefined;
  const replyTokens = new Map<string, string>();

  const endpoints = json.onResponseReceivedEndpoints || [];

  // Get total count, continuation, and reply tokens from endpoints
  for (const endpoint of endpoints) {
    const items = endpoint.reloadContinuationItemsCommand?.continuationItems ||
                  endpoint.appendContinuationItemsAction?.continuationItems || [];
    for (const item of items) {
      if (item.commentsHeaderRenderer) {
        const countText = item.commentsHeaderRenderer.countText?.runs?.[0]?.text || '';
        const countMatch = countText.match(/[\d,]+/);
        if (countMatch) {
          totalCount = parseInt(countMatch[0].replace(/,/g, ''), 10);
        }
      }
      if (item.continuationItemRenderer) {
        nextContinuation = item.continuationItemRenderer.continuationEndpoint?.continuationCommand?.token;
      }
      // Extract reply continuation tokens from comment threads
      if (item.commentThreadRenderer) {
        const thread = item.commentThreadRenderer;
        const vm = thread.commentViewModel?.commentViewModel;
        const commentId = vm?.commentId;
        const replies = thread.replies?.commentRepliesRenderer;
        if (commentId && replies) {
          // Look for continuation token in replies
          const replyContents = replies.contents || [];
          for (const rc of replyContents) {
            const token = rc.continuationItemRenderer?.continuationEndpoint?.continuationCommand?.token;
            if (token) {
              replyTokens.set(commentId, token);
              break;
            }
          }
        }
      }
    }
  }

  // Extract comments from frameworkUpdates (new YouTube API structure)
  const mutations = json.frameworkUpdates?.entityBatchUpdate?.mutations || [];
  const pinnedCommentIds = new Set<string>();

  // First pass: identify pinned comments from commentViewModel
  for (const endpoint of endpoints) {
    const items = endpoint.reloadContinuationItemsCommand?.continuationItems ||
                  endpoint.appendContinuationItemsAction?.continuationItems || [];
    for (const item of items) {
      const vm = item.commentThreadRenderer?.commentViewModel?.commentViewModel;
      if (vm?.pinnedText && vm.commentId) {
        pinnedCommentIds.add(vm.commentId);
      }
    }
  }

  // Second pass: extract comment data
  for (const mut of mutations) {
    const mutPayload = mut.payload?.commentEntityPayload;
    if (!mutPayload) continue;

    const props = mutPayload.properties || {};
    const author = mutPayload.author || {};
    const toolbar = mutPayload.toolbar || {};
    const commentId = props.commentId || '';

    comments.push({
      author: author.displayName || '',
      authorChannelId: author.channelId || '',
      text: props.content?.content || '',
      likes: toolbar.likeCountNotliked || '0',
      replyCount: parseInt(toolbar.replyCount || '0', 10),
      publishedTime: props.publishedTime || '',
      isPinned: pinnedCommentIds.has(commentId),
      isHearted: !!(toolbar.heartActiveTooltip),
      commentId,
      isReply: false
    });
  }

  return { comments, totalCount, continuation: nextContinuation, replyTokens };
}

/**
 * Fetches replies for a comment using its reply continuation token
 */
async function fetchReplies(
  replyToken: string,
  parentId: string,
  visitorData: string,
  clientVersion: string,
  maxReplies: number = 50
): Promise<Comment[]> {
  const replies: Comment[] = [];
  let token: string | undefined = replyToken;
  let pagesFetched = 0;
  const maxPages = 5;

  while (token && replies.length < maxReplies && pagesFetched < maxPages) {
    const payload = JSON.stringify({
      context: {
        client: {
          hl: 'en',
          gl: 'US',
          clientName: 'WEB',
          clientVersion: clientVersion,
          visitorData: visitorData
        }
      },
      continuation: token
    });

    try {
      const response = await httpsRequest({
        hostname: 'www.youtube.com',
        path: '/youtubei/v1/next?prettyPrint=false',
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(payload),
          'User-Agent': WEB_USER_AGENT,
          'Origin': 'https://www.youtube.com'
        }
      }, payload);

      const json = JSON.parse(response);
      pagesFetched++;

      // Extract reply comments from mutations
      const mutations = json.frameworkUpdates?.entityBatchUpdate?.mutations || [];
      for (const mut of mutations) {
        const mutPayload = mut.payload?.commentEntityPayload;
        if (!mutPayload) continue;

        const props = mutPayload.properties || {};
        const author = mutPayload.author || {};
        const toolbar = mutPayload.toolbar || {};

        replies.push({
          author: author.displayName || '',
          authorChannelId: author.channelId || '',
          text: props.content?.content || '',
          likes: toolbar.likeCountNotliked || '0',
          replyCount: 0,
          publishedTime: props.publishedTime || '',
          isPinned: false,
          isHearted: !!(toolbar.heartActiveTooltip),
          commentId: props.commentId || '',
          isReply: true,
          parentId
        });
      }

      // Get next continuation token for more replies
      token = undefined;
      const endpoints = json.onResponseReceivedEndpoints || [];
      for (const endpoint of endpoints) {
        const items = endpoint.appendContinuationItemsAction?.continuationItems || [];
        for (const item of items) {
          if (item.continuationItemRenderer) {
            token = item.continuationItemRenderer.continuationEndpoint?.continuationCommand?.token;
            break;
          }
        }
        if (token) break;
      }
    } catch (err) {
      console.error('[youtube-fetcher] Error fetching replies:', err);
      break;
    }
  }

  return replies.slice(0, maxReplies);
}

/**
 * Fetches comments for a video using YouTube's internal API with pagination support
 */
export async function getComments(options: {
  videoID: string;
  sortBy?: 'TOP_COMMENTS' | 'NEWEST_FIRST';
  limit?: number;
}): Promise<CommentsResult> {
  const { videoID, sortBy = 'TOP_COMMENTS', limit = 20 } = options;

  if (!videoID || typeof videoID !== 'string') {
    throw new Error('Invalid video ID: must be a non-empty string');
  }

  // Get page data for visitorData
  const { visitorData, clientVersion } = await getPageData(videoID);

  // Build initial comments params (0 = TOP_COMMENTS, 1 = NEWEST_FIRST)
  const sortByNum = sortBy === 'NEWEST_FIRST' ? 1 : 0;
  let continuationToken: string | undefined = encodeURIComponent(buildCommentsParams(videoID, sortByNum));

  const allComments: Comment[] = [];
  const allReplyTokens = new Map<string, string>();
  let totalCount = 0;
  const noLimit = limit === 0; // 0 means fetch all

  try {
    // First pass: fetch all top-level comments and collect reply tokens
    while (continuationToken && (noLimit || allComments.length < limit)) {
      const pageResult = await fetchCommentsPage(continuationToken, visitorData, clientVersion);

      if (pageResult.totalCount > 0) {
        totalCount = pageResult.totalCount;
      }

      allComments.push(...pageResult.comments);
      continuationToken = pageResult.continuation;

      // Collect reply tokens
      for (const [commentId, token] of pageResult.replyTokens) {
        allReplyTokens.set(commentId, token);
      }

      // If we got no new comments, stop
      if (pageResult.comments.length === 0) break;
    }

    // Second pass: fetch replies for comments that have them (if we have room)
    if ((noLimit || allComments.length < limit) && allReplyTokens.size > 0) {
      const commentsWithReplies = allComments.filter(c => c.replyCount > 0 && allReplyTokens.has(c.commentId));

      // Collect all replies keyed by parent ID to avoid mutating allComments during iteration
      const repliesByParent = new Map<string, Comment[]>();
      let totalRepliesFetched = 0;

      for (const comment of commentsWithReplies) {
        if (!noLimit && (allComments.length + totalRepliesFetched) >= limit) break;

        const replyToken = allReplyTokens.get(comment.commentId);
        if (!replyToken) continue;

        const remainingSlots = noLimit ? comment.replyCount : Math.min(limit - allComments.length - totalRepliesFetched, comment.replyCount);
        if (remainingSlots <= 0) break;

        const replies = await fetchReplies(replyToken, comment.commentId, visitorData, clientVersion, remainingSlots);
        repliesByParent.set(comment.commentId, replies);
        totalRepliesFetched += replies.length;
      }

      // Merge replies after parent comments (iterate in reverse to keep indices stable)
      const parentIds = [...repliesByParent.keys()];
      for (let i = parentIds.length - 1; i >= 0; i--) {
        const parentId = parentIds[i];
        const replies = repliesByParent.get(parentId)!;
        const parentIndex = allComments.findIndex(c => c.commentId === parentId);
        if (parentIndex !== -1) {
          allComments.splice(parentIndex + 1, 0, ...replies);
        } else {
          allComments.push(...replies);
        }
      }
    }
  } catch (err) {
    console.error('[youtube-fetcher] Error fetching comments:', err);
  }

  return {
    comments: noLimit ? allComments : allComments.slice(0, limit),
    totalCount,
    continuation: continuationToken
  };
}

// ==================== LIVE CHAT SUPPORT ====================

export interface LiveChatMessage {
  id: string;
  author: string;
  authorChannelId: string;
  text: string;
  timestampUsec: string;
  isPaid: boolean;
  paidAmount?: string;
}

export interface LiveChatResult {
  messages: LiveChatMessage[];
  continuation?: string;
  isLive: boolean;
  pollIntervalMs: number;
  videoTitle?: string;
  channelName?: string;
}

/**
 * Extracts live chat continuation token from video page
 */
async function getLiveChatContinuation(videoId: string): Promise<{
  continuation: string;
  isLive: boolean;
  visitorData: string;
  title?: string;
  author?: string;
}> {
  let html: string;

  try {
    html = await httpsRequest({
      hostname: 'www.youtube.com',
      path: `/watch?v=${videoId}`,
      method: 'GET',
      headers: {
        'User-Agent': WEB_USER_AGENT,
        'Accept-Language': 'en-US,en;q=0.9'
      }
    });
  } catch (err) {
    throw new Error(`Failed to fetch video page: ${(err as Error).message}`);
  }

  // Check if live
  const isLive = html.includes('"isLiveContent":true') || html.includes('"isLive":true');

  if (!isLive) {
    throw new Error('This video is not a live stream. Use get_transcript for regular videos.');
  }

  // Extract visitor data
  const visitorMatch = html.match(/"visitorData":"([^"]+)"/);
  const visitorData = visitorMatch?.[1] || '';

  // Extract continuation token for live chat
  const continuationMatch = html.match(/"continuation":"([^"]+)"/);
  if (!continuationMatch) {
    throw new Error('Could not find live chat continuation token. The stream may have ended.');
  }

  // Extract metadata
  const titleMatch = html.match(/"title":"([^"]+)"/);
  const authorMatch = html.match(/"author":"([^"]+)"/);

  return {
    continuation: continuationMatch[1],
    isLive,
    visitorData,
    title: titleMatch?.[1],
    author: authorMatch?.[1]
  };
}

/**
 * Fetches live chat messages from a live stream
 */
export async function getLiveChat(options: {
  videoID: string;
  continuation?: string;
  visitorData?: string;
}): Promise<LiveChatResult & { visitorData: string }> {
  const { videoID } = options;
  let { continuation } = options;
  let visitorData = options.visitorData || '';
  let videoTitle: string | undefined;
  let channelName: string | undefined;

  // If no continuation provided, get it from the page
  if (!continuation) {
    const pageData = await getLiveChatContinuation(videoID);
    continuation = pageData.continuation;
    visitorData = pageData.visitorData;
    videoTitle = pageData.title;
    channelName = pageData.author;
  }

  // Fetch live chat
  const payload = JSON.stringify({
    context: {
      client: {
        clientName: 'WEB',
        clientVersion: DEFAULT_CLIENT_VERSION,
        visitorData: visitorData
      }
    },
    continuation: continuation
  });

  let response: string;
  try {
    response = await httpsRequest({
      hostname: 'www.youtube.com',
      path: '/youtubei/v1/live_chat/get_live_chat?key=AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(payload),
        'User-Agent': WEB_USER_AGENT,
        'Origin': 'https://www.youtube.com'
      }
    }, payload);
  } catch (err) {
    throw new Error(`Failed to fetch live chat: ${(err as Error).message}`);
  }

  const json = JSON.parse(response);

  if (json.error) {
    throw new Error(`YouTube API error: ${json.error.message || 'Unknown error'}`);
  }

  const messages: LiveChatMessage[] = [];
  let nextContinuation: string | undefined;
  let pollIntervalMs = 5000; // Default 5 seconds

  // Extract continuation and poll interval
  const liveChatContinuation = json.continuationContents?.liveChatContinuation;
  if (liveChatContinuation) {
    const continuations = liveChatContinuation.continuations || [];
    for (const cont of continuations) {
      const invalidation = cont.invalidationContinuationData || cont.timedContinuationData;
      if (invalidation) {
        nextContinuation = invalidation.continuation;
        pollIntervalMs = invalidation.timeoutMs || 5000;
        break;
      }
    }

    // Extract messages from actions
    const actions = liveChatContinuation.actions || [];
    for (const action of actions) {
      if (action.addChatItemAction) {
        const item = action.addChatItemAction.item;

        // Regular text message
        if (item.liveChatTextMessageRenderer) {
          const r = item.liveChatTextMessageRenderer;
          const text = (r.message?.runs || []).map((run: any) => run.text || '').join('');

          messages.push({
            id: r.id || '',
            author: r.authorName?.simpleText || '',
            authorChannelId: r.authorExternalChannelId || '',
            text,
            timestampUsec: r.timestampUsec || '',
            isPaid: false
          });
        }

        // Paid message (Super Chat)
        if (item.liveChatPaidMessageRenderer) {
          const r = item.liveChatPaidMessageRenderer;
          const text = (r.message?.runs || []).map((run: any) => run.text || '').join('');

          messages.push({
            id: r.id || '',
            author: r.authorName?.simpleText || '',
            authorChannelId: r.authorExternalChannelId || '',
            text,
            timestampUsec: r.timestampUsec || '',
            isPaid: true,
            paidAmount: r.purchaseAmountText?.simpleText || ''
          });
        }
      }
    }
  }

  return {
    messages,
    continuation: nextContinuation,
    isLive: true,
    pollIntervalMs,
    videoTitle,
    channelName,
    visitorData
  };
}

// ==================== BACKGROUND STREAMING ====================

interface LiveStreamState {
  videoId: string;
  visitorData: string;
  continuation: string;
  pollIntervalMs: number;
  messageBuffer: LiveChatMessage[];
  seenIds: Set<string>;
  isPolling: boolean;
  pollTimer: NodeJS.Timeout | null;
  videoTitle?: string;
  channelName?: string;
  startedAt: number;
  lastPollAt: number;
  totalMessagesFetched: number;
}

// Global state for background streams
const activeStreams: Map<string, LiveStreamState> = new Map();

/**
 * Check if a video is a live stream without throwing
 */
export async function checkIfLive(videoId: string): Promise<{
  isLive: boolean;
  title?: string;
  author?: string;
}> {
  try {
    const html = await httpsRequest({
      hostname: 'www.youtube.com',
      path: `/watch?v=${videoId}`,
      method: 'GET',
      headers: {
        'User-Agent': WEB_USER_AGENT,
        'Accept-Language': 'en-US,en;q=0.9'
      }
    });

    const isLive = html.includes('"isLiveContent":true') || html.includes('"isLive":true');
    const titleMatch = html.match(/"title":"([^"]+)"/);
    const authorMatch = html.match(/"author":"([^"]+)"/);

    return {
      isLive,
      title: titleMatch?.[1],
      author: authorMatch?.[1]
    };
  } catch {
    return { isLive: false };
  }
}

/**
 * Start background polling for a live stream
 */
export async function startLiveChatStream(videoId: string): Promise<LiveChatResult & { streaming: boolean }> {
  // Check if already streaming
  if (activeStreams.has(videoId)) {
    const state = activeStreams.get(videoId)!;
    // Return buffered messages and clear buffer
    const messages = [...state.messageBuffer];
    state.messageBuffer = [];

    return {
      messages,
      continuation: state.continuation,
      isLive: state.isPolling,
      pollIntervalMs: state.pollIntervalMs,
      videoTitle: state.videoTitle,
      channelName: state.channelName,
      streaming: true
    };
  }

  // Start new stream
  const result = await getLiveChat({ videoID: videoId });

  const state: LiveStreamState = {
    videoId,
    visitorData: result.visitorData,
    continuation: result.continuation || '',
    pollIntervalMs: result.pollIntervalMs,
    messageBuffer: [],
    seenIds: new Set(result.messages.map(m => m.id)),
    isPolling: true,
    pollTimer: null,
    videoTitle: result.videoTitle,
    channelName: result.channelName,
    startedAt: Date.now(),
    lastPollAt: Date.now(),
    totalMessagesFetched: result.messages.length
  };

  activeStreams.set(videoId, state);

  // Start background polling
  const poll = async () => {
    if (!state.isPolling) return;

    try {
      const newResult = await getLiveChat({
        videoID: videoId,
        continuation: state.continuation,
        visitorData: state.visitorData
      });

      state.lastPollAt = Date.now();
      state.continuation = newResult.continuation || state.continuation;
      state.pollIntervalMs = newResult.pollIntervalMs;

      // Count new messages before adding to seenIds
      let newMsgCount = 0;

      // Add only new messages to buffer
      for (const msg of newResult.messages) {
        if (!state.seenIds.has(msg.id)) {
          state.seenIds.add(msg.id);
          state.messageBuffer.push(msg);
          state.totalMessagesFetched++;
          newMsgCount++;
        }
      }

      // Cap buffer at 500 messages
      if (state.messageBuffer.length > 500) {
        state.messageBuffer = state.messageBuffer.slice(-500);
      }

      // Cap seenIds at 2000
      if (state.seenIds.size > 2000) {
        const arr = Array.from(state.seenIds);
        state.seenIds = new Set(arr.slice(-1500));
      }

      // Log new messages to stderr
      if (newMsgCount > 0) {
        process.stderr.write(`\n[LIVE] ${state.videoTitle || videoId} | +${newMsgCount} msgs | buffer: ${state.messageBuffer.length} | total: ${state.totalMessagesFetched}\n`);
        const lastMsg = state.messageBuffer[state.messageBuffer.length - 1];
        if (lastMsg) {
          process.stderr.write(`  └─ ${lastMsg.author}: ${lastMsg.text.slice(0, 60)}${lastMsg.text.length > 60 ? '...' : ''}\n`);
        }
      }

    } catch (err) {
      console.error(`[live-chat] Poll error for ${videoId}:`, err);
      // Stream may have ended
      if ((err as Error).message?.includes('ended')) {
        state.isPolling = false;
        return;
      }
    }

    // Schedule next poll
    if (state.isPolling) {
      state.pollTimer = setTimeout(poll, state.pollIntervalMs);
    }
  };

  // Start first background poll after initial delay
  state.pollTimer = setTimeout(poll, state.pollIntervalMs);

  return {
    ...result,
    streaming: true
  };
}

/**
 * Get buffered messages from an active stream
 */
export function getLiveChatBuffer(videoId: string): {
  messages: LiveChatMessage[];
  isStreaming: boolean;
  stats: {
    totalFetched: number;
    bufferSize: number;
    streamDurationMs: number;
    lastPollMs: number;
  };
  videoTitle?: string;
  channelName?: string;
} | null {
  const state = activeStreams.get(videoId);
  if (!state) return null;

  // Get and clear buffer
  const messages = [...state.messageBuffer];
  state.messageBuffer = [];

  return {
    messages,
    isStreaming: state.isPolling,
    stats: {
      totalFetched: state.totalMessagesFetched,
      bufferSize: messages.length,
      streamDurationMs: Date.now() - state.startedAt,
      lastPollMs: Date.now() - state.lastPollAt
    },
    videoTitle: state.videoTitle,
    channelName: state.channelName
  };
}

/**
 * Stop background polling for a live stream
 */
export function stopLiveChatStream(videoId: string): {
  stopped: boolean;
  finalMessages: LiveChatMessage[];
  stats: {
    totalFetched: number;
    streamDurationMs: number;
  };
} | null {
  const state = activeStreams.get(videoId);
  if (!state) return null;

  state.isPolling = false;
  if (state.pollTimer) {
    clearTimeout(state.pollTimer);
  }

  const finalMessages = [...state.messageBuffer];
  const stats = {
    totalFetched: state.totalMessagesFetched,
    streamDurationMs: Date.now() - state.startedAt
  };

  activeStreams.delete(videoId);

  return {
    stopped: true,
    finalMessages,
    stats
  };
}

/**
 * List all active streams
 */
export function listActiveStreams(): Array<{
  videoId: string;
  videoTitle?: string;
  channelName?: string;
  isPolling: boolean;
  bufferSize: number;
  totalFetched: number;
  streamDurationMs: number;
}> {
  return Array.from(activeStreams.values()).map(state => ({
    videoId: state.videoId,
    videoTitle: state.videoTitle,
    channelName: state.channelName,
    isPolling: state.isPolling,
    bufferSize: state.messageBuffer.length,
    totalFetched: state.totalMessagesFetched,
    streamDurationMs: Date.now() - state.startedAt
  }));
}

